apiVersion : apps/v1
kind: Deployment
metadata:
  name: jaganrajagopaljenkinswithdockercomposeup 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaganrajagopaljenkinswithdockercomposeup
  template:
    metadata:
      labels:
        app: jaganrajagopaljenkinswithdockercomposeup 
    spec:
      containers:
        - name: jaganrajagopaljenkinswithdockercomposeup 
          image: 11122233345/dotnetwebapptraining
          #dotnetacrlatest.azurecr.io/dotnetacrlatest:latest
          #dotnetacrlatest.azurecr.io/jaganrajagopaljenkinswithdockercomposeup
          #just comments
          #dotnetacrv1.azurecr.io/jaganrajagopaljenkinswithdockercomposeup
          ports:
          - containerPort: 80
